#!/bin/bash

echo "navigation to target folder"
cd /var/www/pw_comments

echo "enabling xdebug"
enable_xdebug

echo "running unit tests with coverage"
XDEBUG_MODE=coverage ./tools/phpunit -c Build/phpunit.xml --do-not-cache

echo "disabling xdebug"
disable_xdebug
