#!/bin/bash

echo "navigation to target folder"
cd /var/www/pw_comments

echo "disabling xdebug"
disable_xdebug

echo "running functional tests"
XDEBUG_MODE=debug ./tools/phpunit -c Build/phpunit.functional.xml --testsuite "Functional Tests"
