#!/bin/bash

echo "navigation to target folder"
cd /var/www/pw_comments

echo "disabling xdebug"
disable_xdebug

echo "running unit tests"
XDEBUG_MODE=coverage ./vendor/bin/phpunit -c Build/phpunit.functional.xml --testsuite "Functional Tests"
