version: "3.6"
services:
    web:
        environment:
            - EXTENSION_KEY=pw_comments
            - PACKAGE_NAME=teamneusta/pw_comments

            - TYPO3_INSTALL_DB_DRIVER=mysqli
            - TYPO3_INSTALL_DB_USER=root
            - TYPO3_INSTALL_DB_DBNAME=db
            - TYPO3_INSTALL_DB_PASSWORD=root
            - TYPO3_INSTALL_DB_HOST=db
            - TYPO3_INSTALL_DB_PORT=3306
            - TYPO3_INSTALL_DB_UNIX_SOCKET=
            - TYPO3_INSTALL_DB_USE_EXISTING=0
            - TYPO3_INSTALL_ADMIN_USER=admin
            - TYPO3_INSTALL_ADMIN_PASSWORD=Admin123!
            - TYPO3_INSTALL_SITE_NAME=EXT:pw_comments Dev Environment
            - TYPO3_INSTALL_SITE_SETUP_TYPE=site
            - TYPO3_INSTALL_WEB_SERVER_CONFIG=apache
        volumes:
            - type: bind
              source: ../
              target: /var/www/pw_comments
              consistency: cached
            - type: bind
              source: ../vendor
              target: /var/www/html/v12/vendor
              consistency: cached
            - v12-data:/var/www/html/v12
volumes:
    v12-data:
        name: "${DDEV_SITENAME}-v12-data"
